@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderRift.automation.driver;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;