@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderRift.common.slots;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;