@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.enderrift.plugins;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;