@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderRift.automation.iface;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;