@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.enderrift;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;