@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderRift.automation.proxy;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;