@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.enderRift.automation.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;